# SITE SETTINGS
title: 'two-brain · webdesign'
description: Hallo! Ich bin Martin, freier Webdesigner aus Freiburg und erschaffe anspruchsvolle sowie benutzerfreundliche Webseiten. Ihre auch?
last_update: 2017/04/23

# ABOUT
email: hello@twobrain.io
github: two-brain
twitter: twobrain_design

# SEO
# google_site_verification:

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
source: source
destination: build
include: ['_pages']
exclude: ['_pages/partials']

# PLUGINS
gems:
  - jekyll-email-protect

# TECHNOLOGY
standards: HTML5, CSS3
components:
development: Jekyll, Gulp, Webpack, Sass
